# Generated by Django 4.1.5 on 2023-01-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_choice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='link',
            field=models.FileField(upload_to=''),
        ),
    ]
