# Generated by Django 4.1.5 on 2023-01-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_choice_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='f_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
